//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.AOPA.Structure.Webparts.Minuta_Lista_E_Edicao {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Minuta_Lista_E_Edicao {
        
        protected global::Microsoft.SharePoint.WebControls.RenderingTemplate resnd;
        
        public static implicit operator global::System.Web.UI.TemplateControl(Minuta_Lista_E_Edicao target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.ListViewByQuery @__BuildControl__control3() {
            global::Microsoft.SharePoint.WebControls.ListViewByQuery @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ListViewByQuery();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "quadroMinuta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::Microsoft.SharePoint.WebControls.ListViewByQuery @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.RenderingTemplate @__BuildControlresnd() {
            global::Microsoft.SharePoint.WebControls.RenderingTemplate @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.RenderingTemplate();
            this.resnd = @__ctrl;
            @__ctrl.Template = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "resnd";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.AOPA.Structure.Webparts.Minuta_Lista_E_Edicao.Minuta_Lista_E_Edicao @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<style>
    .div_tb {
        width:800px;
        margin:auto;
    }

    .margin-div {
        margin-bottom:20px;
        width:100%;
        float:left;
    }
    /*.nomeSite {
        display:none;
    }*/
</style>

<script type=""text/javascript"">

</script>



        "));
            global::Microsoft.SharePoint.WebControls.RenderingTemplate @__ctrl1;
            @__ctrl1 = this.@__BuildControlresnd();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n   \r\n\r\n   <div style=\"margin-top:40px; margin-bottom:20px; width:1000px;\">\r\n   " +
                        "    <div class=\"nomeSite\">\r\n            <span class=\"ms-core-pageTitle\">Adiciona" +
                        "r Novo Item de Minuta</span>\r\n        </div>\r\n   </div>\r\n\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
