//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnas.AOPA.Structure.Webparts.Minuta_Display {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class Minuta_Display {
        
        protected global::System.Web.UI.WebControls.Button add_item_minuta;
        
        protected global::System.Web.UI.WebControls.Button fazer_analise_diretorias;
        
        protected global::System.Web.UI.WebControls.Button fazer_consolidacao;
        
        protected global::System.Web.UI.WebControls.Button aprovacao_minuta;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl actionsMinutaNIouPolitica;
        
        public static implicit operator global::System.Web.UI.TemplateControl(Minuta_Display target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControladd_item_minuta() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.add_item_minuta = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "add_item_minuta";
            @__ctrl.Text = "Adicionar/Editar itens na Minuta";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.add_item_minuta_Click);
            @__ctrl.Click += new System.EventHandler(this.add_item_minuta_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlfazer_analise_diretorias() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.fazer_analise_diretorias = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fazer_analise_diretorias";
            @__ctrl.Text = "Análise dos Itens Minuta";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.fazer_analise_diretorias_Click);
            @__ctrl.Click += new System.EventHandler(this.fazer_analise_diretorias_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlfazer_consolidacao() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.fazer_consolidacao = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fazer_consolidacao";
            @__ctrl.Text = "Consolidar Itens da Minuta";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.fazer_consolidacao_Click);
            @__ctrl.Click += new System.EventHandler(this.fazer_consolidacao_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlaprovacao_minuta() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.aprovacao_minuta = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "aprovacao_minuta";
            @__ctrl.Text = "Aprovação e Publicação da Minuta";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.aprovacao_minuta_Click);
            @__ctrl.Click += new System.EventHandler(this.aprovacao_minuta_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlactionsMinutaNIouPolitica() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("fieldset");
            this.actionsMinutaNIouPolitica = @__ctrl;
            @__ctrl.ID = "actionsMinutaNIouPolitica";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <legend>Ações dos Items da Minuta</legend>\r\n    <div>\r\n        <!-- Fase in" +
                        "iciaç -->\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl1;
            @__ctrl1 = this.@__BuildControladd_item_minuta();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\r\n        <!-- Fase preparação e Ajuste-->\r\n        \r\n        <!-- Fa" +
                        "se do Quadro de Analise para areas-->\r\n        \r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlfazer_analise_diretorias();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\r\n        <!-- Fase Consolidação -->\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl3;
            @__ctrl3 = this.@__BuildControlfazer_consolidacao();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\r\n        <!-- proposição -->\r\n        &nbsp;&nbsp;\r\n        <!-- Fas" +
                        "e Aprovação e Emissão da PRD-->\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl4;
            @__ctrl4 = this.@__BuildControlaprovacao_minuta();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;&nbsp;\r\n        <!-- Fase Publicar Ato-->\r\n        &nbsp;&nbsp;\r\n        <!" +
                        "-- Revisar Minuta-->\r\n        \r\n    </div>\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Furnas.AOPA.Structure.Webparts.Minuta_Display.Minuta_Display @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<script type=""text/javascript"">
    function OpenDialog(url, title) {
        var options = {
            url: url,
            title: title,
            dialogReturnValueCallback: Function.createDelegate(null, CloseDialogCallback)
        };
        SP.SOD.execute('sp.ui.dialog.js', 'SP.UI.ModalDialog.showModalDialog', options);
    }

    function CloseDialogCallback(dialogResult, returnValue) {
        //SP.SOD.execute('sp.ui.dialog.js', 'SP.UI.ModalDialog.RefreshPage', SP.UI.DialogResult.OK);
        location.reload();
    }
    </script>

<style type=""text/css"">
    fieldset {
        padding:20px;
    }
</style>

"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlactionsMinutaNIouPolitica();
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
